### ISSUE TITLE
Making a Main Server Exporter

### ISSUE THREAD

**Issue by esha0281** [wildstang/WildRank#268]
Dear Developer: 

We have connected PY(server), to the main link to a main computer --> but its giving us an issues of error unable to connect to server, is this because we are hosting on replit, should we host on a dedicated server site?

**Comment by fruzyna** [comment]
Is this when using the raw data zip transfer tool built into WildRank? If so, as long as you are trying to push to the same server you are connecting to the app through there should be no issues. The same port is used for both operations. Pushing from an app running off of one server, to a different can be problematic in certain browsers.
